# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]

jobs:
  vueclient:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: echo All tests passed!

      - name: Push to prod branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: prod
          FOLDER: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
  

